name: Scrape Jobs Every Hour

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape_jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Set Job Roles and Calculate Role for Current Hour
        id: job_role
        run: |
          declare -a JOB_ROLES=(
            "Software Engineer"
            "Software Developer"
            "Front-End Developer"
            "Back-End Developer"
            "Full-Stack Developer"
            "Mobile App Developer"
            "Embedded Software Engineer"
            "Game Developer"
            "Cloud Engineer"
            "DevOps Engineer"
            "Machine Learning Engineer"
            "AI Engineer"
            "Data Engineer"
            "Data Analyst"
            "IT Support Engineer"
            "Software Test Engineer"
            "UI/UX Designer"
            "Blockchain Developer"
            "IoT Engineer"
            "Web Developer"
          )

          # Calculate the base index for this hour
          HOUR_INDEX=$(( ($(date +%-H) * 20) / 24 ))

          # Select three job roles for this hour
          ROLE_1="${JOB_ROLES[$HOUR_INDEX]}"
          ROLE_2="${JOB_ROLES[$(( (HOUR_INDEX + 1) % 20 ))]}"
          ROLE_3="${JOB_ROLES[$(( (HOUR_INDEX + 2) % 20 ))]}"

          # Convert to URL encoded format (replace spaces with %20)
          ROLE_1_URL=$(echo $ROLE_1 | sed 's/ /%20/g')
          ROLE_2_URL=$(echo $ROLE_2 | sed 's/ /%20/g')
          ROLE_3_URL=$(echo $ROLE_3 | sed 's/ /%20/g')

          # Store values for later steps
          echo "ROLE_1=$ROLE_1_URL" >> $GITHUB_ENV
          echo "ROLE_2=$ROLE_2_URL" >> $GITHUB_ENV
          echo "ROLE_3=$ROLE_3_URL" >> $GITHUB_ENV

          echo "Selected job roles: $ROLE_1, $ROLE_2, $ROLE_3"

      - name: Make HTTP Request for Role 1
        run: |
          echo "Running search for: ${{ env.ROLE_1 }}"
          curl -X GET "https://job-scraper.up.railway.app/scrape-jobs?search=${{ env.ROLE_1 }}&resultcount=200"

      - name: Wait for 1 Minutes
        run: sleep 60  # Waits 3 minutes

      - name: Make HTTP Request for Role 2
        run: |
          echo "Running search for: ${{ env.ROLE_2 }}"
          curl -X GET "https://job-scraper.up.railway.app/scrape-jobs?search=${{ env.ROLE_2 }}&resultcount=200"

      - name: Wait for Another 1 Minutes
        run: sleep 60  # Waits another 3 minutes

      - name: Make HTTP Request for Role 3
        run: |
          echo "Running search for: ${{ env.ROLE_3 }}"
          curl -X GET "https://job-scraper.up.railway.app/scrape-jobs?search=${{ env.ROLE_3 }}&resultcount=200"
